version: '3'
services:
  python3:
    restart: always
    build: .  # Dockerfileをimageとして読み込んでいるという意味
    container_name: 'python3'
    ports:
      - 5000:5000
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/python_app
    command: >-
      bash -c 'pip install --root-user-action=ignore -r /root/python_app/requirements.txt; python3'