version: '3'
services:
  python3:
    restart: always
    build: .  # Dockerfileをimageとして読み込んでいるという意味
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:$HOME/python_app