version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    ports:
      - 5000:5000
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/python_app
    command: >-
      bash -c 'cd /root/python_app; pip install --root-user-action=ignore -r ./requirements.txt; python ./app.py'