version: '3'
services:
  python3:
    restart: always
    build: .  # Dockerfileをimageとして読み込んでいるという意味
    container_name: 'python3'
    ports:
      - 8080:8080
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/python_app
    # 動作確認用にlsコマンドを実行している
    command: >-
      bash -c 'pip install --root-user-action=ignore -r /root/python_app/requirements.txt; ls ./python_app; python ./python_app/app.py' 